### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by newcherryberry** [hassantsyed/registration#1]
Hi Hassan,
So sorry if this is a bad repo to do this on, but I cannot find another way to contact you! I need some help with a project you have worked on before (OpenAnimate). Please let me know if I can email you or if you feel more comfortable emailing me.
Thanks,
Maylin

**Comment by hassantsyed** [comment]
Hey this is the funniest way I've seen someone get in contact with me, but it totally worked!
how can I help?
feel free to email me at: hassantsyed@gmail.com
